baseURL = 'https://daviddehoog.github.io'
languageCode = 'en-au'
title = 'daviddehoog.github.io'
theme = 'ananke'

[taxonomies]
    topic = 'topics'
    status = 'status'

sectionPagesMenu = 'main'

[params]
    mainSections = ['posts']
