baseURL = 'https://daviddehoog.github.io'
languageCode = 'en-au'
title = 'daviddehoog.github.io'
theme = 'ananke'

[taxonomies]
    topic = 'topics'
    status = 'status'

sectionPagesMenu = 'main'

[menus]
    [[menus.main]]
        name = 'timeline'
        pageRef = '/timeline'
        weight = 20

[params]
    mainSections = ['posts']
    custom_css = ['timeline.css']